### PR TITLE
Neural Networks from Scratch - P.3 The Dot Product 

### PR DESCRIPTION
**Pull request by mallik18**
Neural Networks from Scratch - P.3 The Dot Product  using Arrays in C language

### CODE REVIEW

**Comment by mallik18** [comment]
This is my first contribution to opensource project so please let me know if there are any issues.

**Comment by Sentdex** [comment]
Hrmm, the main issue I have is there's already a p003 for C: https://github.com/Sentdex/NNfSiX/blob/master/C/p003-Dot%20Product.c

Is there a reason why this one is superior?

**Comment by mallik18** [comment]
I don't think my code is superior , it's just very simple to read without any other functions and pointers ,as it's my very first contribution to opensource so I kept it simple.

Please let me know if there are any issues with the code, so that I can be better next time.

**Comment by Sentdex** [comment]
ATM, we're going with 1 version per language. I can leave this open JIC we change our minds, it's something we're discussing, but I fear a giant mess if we allow for a bunch of variants of each language. Since we already have a p003, I would say we'd just stick with that, but if we can come up with a clean way to have multiple variants per language, then I might reconsider this one.

**Comment by mallik18** [comment]
That's great , I will try my best to submit the solutions to the problems as soon as possible in coming days.

**Pull request closed without merging**
