### PR TITLE
C code P.3 The Dot Product

### PR DESCRIPTION
**Pull request by Devilbinder**
Code to calculate the dot product for part 3.

Changed the previous tutorial datatypes to double for better resolution

### CODE REVIEW

**Comment by Sentdex** [comment]
@Dmendoza99 Could you weigh in on these changes and submission?

**Comment by Devilbinder** [comment]
Change from float to double is for precision. [This ](https://stackoverflow.com/questions/2386772/what-is-the-difference-between-float-and-double)answer from stackoverflow should be sufficient.

Fixing the size of the array is better practice, if the size is known. Also added the defines so the sizes can easily be changed.

The code final outputs.
nur output: 4.800000 1.210000 2.385000

Any more questions please ask.

**Comment by Dmendoza99** [comment]
Well I'm seen he changed the floats for doubles, I don't use doubles because of what I know they have a bigger size than a float. 

But after that I see good practices in the file he added in

**Comment by Devilbinder** [comment]
The performance impacted of using doubles is usually negligible with modern systems. I was under the assumption the code would run in a desktop environment where ram is definitely not an issue. Basically I will pick precision over RAM if the application allows for it. 

I personal only RAN out of ram working with displays on emended systems.

**Pull request merged**
