### PR TITLE
C P.5 Hidden Layer Activation Functions

### PR DESCRIPTION
**Pull request by Devilbinder**
~~Spiral data was dumped using Python please reference the ReadMe.
Please note that there are rounding errors when loading the spiral data.
Looking for a better method to load the data in with vanilla C.~~

Commit 78c3c8491b39bc76a872e6321bf482926b0a25e0 has rendered the above statement invalid.
Part 6 is also added 1161126bb11f4c45751cf2612d1f08e7968e509a

### CODE REVIEW

**Comment by daniel-kukiela** [comment]
Would it be possible to keep a flat file structure (no subdirectories) and use the function to generate the data instead of generating them to the file first? This will better follow tutorials and what we are trying to achieve here. Thank you!

**Comment by Devilbinder** [comment]
@daniel-kukiela Reworked part 5 to a single file b64443e654dc8184a8a4801004f6183335278670. Also reworked part 4 e3eb50ea0cb8b23e783fcebdaf6acd09f3f3b0cd. Removed the layer depancy on the batch size. 

Sorry for the commit spam fixing spelling errors.

**Comment by daniel-kukiela** [comment]
Thank you!
I'm about to accept it, but what about the spiral data?

**Comment by Devilbinder** [comment]
Added the non hard coded spiral data generation.
Renamed one of the files seed comment 78c3c8491b39bc76a872e6321bf482926b0a25e0.

I'll do part 6 some time later this week.

**Comment by daniel-kukiela** [comment]
Looks good to me.
Thank you for these changes, updates, and new parts! <3

**Pull request merged**
