### PR TITLE
First three lessons in Idris

### PR DESCRIPTION
**Pull request by witt3rd**
Following the Python style (i.e., non-idiomatic Idris)

### CODE REVIEW

**Comment by daniel-kukiela** [comment]
Hi,
Thank you for this submission.
For various reasons we need to keep a full and complete lesson code in a single file, could you please update your implementation according to this?

**Comment by witt3rd** [comment]
Lesson 4 in Python includes:
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data  # See for code: https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c

Idris has no "numpy" equivalent, which is why I created a util module.  You are asking me to essentially inline what the Python version imports?

**Comment by daniel-kukiela** [comment]
If there is some external package that you can simply install (like `pip install numpy` for example in Python), then you are free to use it of course. If you need to create some code by hand - yes, please contain it within this file. I understand that this code is going to be repeated in the next parts, but that's desired, and also solves multiple possible issues in the future (someone else taking over is original maintainer stop committing solutions, backward compatibility issues, maintain issues, etc). I hope that this makes sense for you :)

**Comment by daniel-kukiela** [comment]
Hey,
Will you update your code to follow the guidelines?
I'd like to merge this into the repository, but I don't feel like pushing updates by myself for this language :)

**Pull request closed without merging**
