### PR TITLE
Adds Awk scripts

### PR DESCRIPTION
**Pull request by S0AndS0**
Note, if ya want the more complex examples that respond to command-line parameters within the [`awk-utilities/machine-learning-examples`](https://github.com/awk-utilities/machine-learning-examples) repository too, then feel free to request'em

### CODE REVIEW

**Comment by Sentdex** [comment]
Mr @daniel-kukiela ?

**Comment by S0AndS0** [comment]
Who?...

Small aside, I just checked the `Files changed` section and am not sure why GitHub is showing changes other than the added Awk scripts, perhaps merging `c59591b` alone would be cleaner for commit history.

**Comment by daniel-kukiela** [comment]
> Who?...
Me :) Since I answered you previously.

Now all looks ok!

Answering your first question - for this repository the goal is just to follow tutorial code, but we'll have that in mind, thank you.

**Comment by S0AndS0** [comment]
Groovy and glad it's acceptable.

Indeed, I'll try to submit PRs that are closer to existing code... however, as Awk verson 3 and lower don't do multi-dimensional arrays I've a strong suspicion that there'll be some divergence to workaround this limitation.

Y'all are certainly welcome, and I'm looking forward to following along with the rest of this series.

**Pull request merged**
