### PR TITLE
p005-ReLU-Activation_Spiral_Dataset C#

### PR DESCRIPTION
**Pull request by tanaimarin**
Added Spiral Dataset data from tutorial p005 to C#
use MathNet.Numerics to handle vector and matrix operations.

### CODE REVIEW

**Comment by daniel-kukiela** [comment]
Hi,
We already have a submission for this part. Is there any reason why we should replace it with your implementation?

**Comment by tanaimarin** [comment]
Hi Daniel,
Thanks for reaching out. Yes I noticed there was a submission for that part
already, however that submission doesn't includes the spiral dataset.
In the versiob I created the data set is implemented the same way as innthe
python example and therefore makes it more compatible with the book and I
assume the rest of the videos coming next.
Let me know what you think.


Cheers,

Tanai

**Comment by daniel-kukiela** [comment]
@harigovind511 Since you implemented part 5, what do you think about it?

**Comment by daniel-kukiela** [comment]
I'm going to accept this and replace the existing file.
Thank you for your submission!

**Pull request merged**
