### PR TITLE
Using the Power of Google Colaboratory

### PR DESCRIPTION
**Pull request by AnonymousPyro**
# Getting Started with Google Colaboratory
By using Google Colaboratory anyone can harnesss the power of python from their browsers
They get to use GPU's and TPU's (Limited) for free offered by Google.
I Think this might be the best way to keep track of this Series as not all ( Including me! ) can afford for more computational power. So I thought this might be the best way to go with this...

### CODE REVIEW

**Comment by AnonymousPyro** [comment]
Check the Python folder for the `nnfs.ipynb` file...

**Comment by AnonymousPyro** [comment]
[`The File`](https://colab.research.google.com/github/AnonymousPyro/NNfSiX/blob/master/nnfs.ipynb)  
Click it and Edit => save a copy to Github => And Eureka!!

**Comment by clubPenguin420** [comment]
I personally am using repl.it

**Comment by AnonymousPyro** [comment]
`repl.it` is `not so powerful,` I personally not like using repl.it, In Google Colab you can use` GPU's` and `TPU's` (Tensor Processing Units ) for free, to train `ML models`, **I suggest you to explore the advantages of using Colab, It simply awesome. !!!**

**Comment by daniel-kukiela** [comment]
So the problem that we have here is that for result repeat-ability, and not now yet, but soon, you should avoid interactive shells, including Notebooks. Random number generators cannot be reran freely as they will return different numbers. You would have to restart the kernel every change and rerun all cells (with some exceptions, but you need to know how the notebook works to be able to follow this way).

I'm not sure what we should do with this, as this is basically Python but in a form we're going to not recommend.

**Comment by AnonymousPyro** [comment]
random number generators have what is know as a seed, or random state. So they will provide the same number very time.

**Comment by daniel-kukiela** [comment]
Of course, and that's why we are setting a seed.

But I'm sure that you know how that works and how easy it is to get screwed with interactive shell if you're unaware, and 99% of people will be unaware of possible issues.

The thing is that you will have to run all the cells that are using `np.rand` only once per kernel and in exact order, so you;re not allowed to rerun any cells containing layer initialization or dataset creation, and you are not allowed to run them out of order. That's in contrary to interactive shells which example the notebook actually is of.

We are sure that most people will get confused and will start asking why they cannot replicate our results, and it'll be difficult to explain.

**Comment by AnonymousPyro** [comment]
This is available in the Internet anyone with a google account can view it save a copy and also edit it, and the most interesting part is running it in a browser.

Notebooks allow us to run each line separately, and the results can be seen for each every line.
and connecting them with the Google Colab feature, Notebooks could be ran in a browser, and can also use Computing Resources ( GPUs, TPUs, 12GB RAM )

**Comment by AnonymousPyro** [comment]
These notebooks can make people engage in the content.

**Comment by daniel-kukiela** [comment]
> Notebooks allow us to run each line separately

And that's exactly what you shouldn't do within this code if you follow our tutorial

**Comment by AnonymousPyro** [comment]
I think there is a solution to the problem of running all cells in a order.
There is an option called ` restart kernel and run all cells `.

**Comment by daniel-kukiela** [comment]
I'm personally using Jupyter Lab a lot. It has many use-cases, but cannot be used for everything and in any case. Because of how it works, it has also many limitations. They are visible here, we really should not propose to people to use interactive shells as they can harm more than help in case of this tutorial :)

**Comment by daniel-kukiela** [comment]
> There is an option called restart kernel and run all cells.

But you have to know about it and be aware of it and know that you need to do that every change then it does not differ from a regular script, like you do not benefit from Notebook itself.

**Comment by AnonymousPyro** [comment]
Regular Script
---
If we use them we have to run the whole program to find a bug or some sort.
---
Notebooks
---
These are very helpful in writing bug less code ( less prone to them ),
U can convert this notebook to a .py ( regular script file ) later.

This is just my personal opinion as a fan of Sentdex.

**Comment by daniel-kukiela** [comment]
People tend to think that Notebook is a golden choice for every piece of code, along to Anaconda and venvs that are all of the best practice to use. Don't get me wrong here, I'm just trying to say why Notebook is a bad choice in this case.

You can run this code and follow a whole tutorial on anything. If you have a device that can run a browser, it most likely can run Python, thus you can follow the tutorial fully.

**Comment by daniel-kukiela** [comment]
> If we use them we have to run the whole program to find a bug or some sort.

And we really should in this case

I know how Notebooks are working, and as I said I'm using Jupyter Lab a lot. Thus how I know that we should avoid using it here. The same info is going to be said inn a video tutorial as well as going to be written in our book.

I'm not against the Notebook in general, it;s just it won;t work in this case, not in the way you think it will at least, sir :)

**Comment by AnonymousPyro** [comment]
Cool, I get it 
Thanks for seeing it.

**Comment by daniel-kukiela** [comment]
FYI - even when we knew that already, we have been talking about this.  Thank you for contribution here!

**Pull request closed without merging**
