### PR TITLE
Add p005-ReLU-Activation.go, spiral data gen and plotting

### PR DESCRIPTION
**Pull request by mbdeveci**

### CODE REVIEW

**Comment by Poup2804** [comment]
You could also use `floats.Span()` from "[gonum.org/v1/gonum/floats](https://pkg.go.dev/gonum.org/v1/gonum/floats)" instead of defining `linspace()`.

**Comment by mbdeveci** [comment]
didn't know that, thx

**Comment by daniel-kukiela** [comment]
Would you consider keeping it in a single file? I think that it will be easier to maintain here this way and will follow other implementations.

**Comment by mbdeveci** [comment]
sure, ill do that asap

**Comment by daniel-kukiela** [comment]
Great, thank you!

**Pull request merged**
