### PR TITLE
P004 swift submission

### PR DESCRIPTION
**Pull request by robbiemu**

### CODE REVIEW

**Comment by robbiemu** [comment]
Wondering if there was a standard implementation of seeded gaussian distributions so we could all get comparable outputs

**Comment by Abemarkar23** [comment]
Wouldn't it be better to use the built in `dot(_:_:)` method rather than remaking it?

**Comment by robbiemu** [comment]
it certainly sounds like it would be... You're not talking about this [dot function](https://developer.apple.com/documentation/simd/1425023-dot) are you? That is very explicitly for vectors of 4 numbers. (Actually, what it is about is SIMD: [check it out](https://swiftrocks.com/using-simd-vector-types-in-swift.html) and the original [swift proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0229-simd.md))... So you might ask, could we leverage SIMD, using typical padding approaches so it works when our vectors are not %4==0 ? Sure, there's a standard approach to that sort of thing, and it _does_ stand to give a performance benefit. But, no, that is even less legible.

**Comment by daniel-kukiela** [comment]
@DelSquared Are you going to continue implementing it, or can we accept robbiemu's submissions?

**Comment by DelSquared** [comment]
You can accept it :)

**Comment by daniel-kukiela** [comment]
Thank you!

**Pull request merged**
