### PR TITLE
Update p003-Dot-Product.py

### PR DESCRIPTION
**Pull request by ikostan**
A few calculation samples added: 
1. calculation using standart Python list
2. calculation using NumPy Array
3. calculation using Dot Product

### CODE REVIEW

**Comment by ikostan** [comment]
Hi there.

I added a few examples in order to stress the difference between defferent data types and calculations. Hope you find it useful.

Thanks.

**Comment by Sentdex** [comment]
While I like this concept, I am not sure that we want to allow in alternates like this, since that would open the door to alternates in all languages, and then organization becomes a serious issue.

**Comment by ikostan** [comment]
In any case, the original idea is yours. I mean you showed in the last video how to use Python regular loop in order to calculate the result...

**Comment by Sentdex** [comment]
Going to close this, trying to keep each file as simple as possible. While you're right that we showed multiple ways to achieve this, I am trying to keep other languages to reproducing the py versions of files. If we have 2+ ways of doing the same thing, it will be more confusing to adhere to that and just follow along for others.

**Pull request closed without merging**
