### PR TITLE
Add p004 Swift Implementation

### PR DESCRIPTION
**Pull request by Andrew-Pynch**

### CODE REVIEW

**Comment by Andrew-Pynch** [comment]
@Sentdex This implementation more closely matches what you are doing in the video series. Please merge unless you have suggestions I need to re-implement.

I would love to continue making these for the duration of this series.

**Comment by robbiemu** [comment]
Andrew does this require swift for tensorflow (I believe that it does)? Or can you give the arena or nef command I need to generate the playground that can run it?

I like the simplicity of this approach but do note a couple of concerns:

1. It does appear to require swift for tensorflow.. in which can we can just import numpy from python directly. And, I thought the point of this topic was specifically to do the work without using libraries like tensorflow.
2. there's no gaussian random number _seed_ .. I bet you can fix that.

**Comment by Andrew-Pynch** [comment]
Hi Robert!

Yes, this does require Swift for Tensorflow but this is not dissimilar to what sentdex is doing in the video series. While he initially shows how to perform certain operations, after the explanations have been given he resorts to using external libraries like numpy. 

Maybe we can import numpy that feels less swifty than using the Swift for Tensorflow module which is the closest counterpart to a library like numpy.

Honestly, I am hoping somebody creates a nice library in swift for doing numpy like operations.

**Comment by robbiemu** [comment]
I think the python can only be imported cleanly , to be able to use bumpy, with swift for tensorflow. I wouldn’t be against using a separate folder for swift for tensorflow, But since it is a literally a separate language I think it is not good for swift

**Comment by Andrew-Pynch** [comment]
Well, I don't think importing numpy libraries is either. Why even write a swift version if we are just using 50% python code? 

@robbiemu I have a solution lets to reimplement numpy from scratch in swift :D

@Sentdex What is your opinion on this? Do we really need a separate folder if we are using Swift for Tensorflow? All of the deep learning people using swift are going to have familiarity with this technology. I don't think it's unreasonable to use but ultimately it's your call.

**Comment by Andrew-Pynch** [comment]
Ahh sorry for the misunderstanding. To be honest my only experience with swift has been using the S4TF module, I honestly didn't know it was a separate language. I thought it was a library for Swift.

I will close this PR and re-open with another folder :-) Nice work on doing lots of the other reimplementationsf rom scratch. They look great.

**Comment by robbiemu** [comment]
please do - This all is just my opinion but, I think there is some real merit to a swift for tensorflow variant. Tensorflow is a _big_ name in this field. The fact that they are putting their full weight into bringing it to Swift carries a lot of gravity and value to that implementation: long story short, even more than a typescript version, I think a swift for tensorflow version is merited.

Eventually, their changes might become a core part of swift, and then it won't be a variant any more. That appears to be the desire of some of the core developers. It just hasn't happened yet.

**Comment by Andrew-Pynch** [comment]
Agreed. Especially with people like Chris Lattner heading up the project. They are putting so much effort into making this the best possible tool they can! Thanks for the feedback man.

**Pull request closed without merging**
