### PR TITLE
Java Added P004Layer with NeuralNetwork, NeuralLayer and Utils class.

### PR DESCRIPTION
**Pull request by khushit-shah**
Added 4 classes,
1. Utils                   => Used for matrix manipulation.
2. NeuralLayer      => Represents a layer. 
3. NeuralNetwork  => Stores All Layer and has forward() method.
4. P004Layer.java => Created A Network with two layer, Shows how to use NeuralNetwork, NeuralLayer and Utils

### CODE REVIEW

**Comment by Sentdex** [comment]
The issue with doing this, is things are going to be getting very messy, very fast, if you have a variety of files like this, per part. 

If you want, you can do this is you make a directory called pXXX (part number) + the descriptive name, and inside that directory are the multiple files you're associating as a package for that specific part.

**Comment by khushit-shah** [comment]
I can also create Layer_Dense in one file and "Utils" file will be helpful through-out the series.
Maybe it is better to follow the video, I thought of implementing with good programming practice.

**Comment by khushit-shah** [comment]
@Sentdex Format the pull request as per the video.

**Comment by daniel-kukiela** [comment]
@GyanendroKh Are you going to continue your implementation or should we accept this

**Comment by daniel-kukiela** [comment]
@khushit-shah I see your previous conversation, but at the moment we need to make some decisions. Putting code into separate files can be problematic in the future, especially when multiple people commit their code for one language. I'd liek to ask you to keep a single and complete file per each part - this way we can ensure that everyone can grab given file and run it without running into different issues like backward compatibility.

**Comment by khushit-shah** [comment]
I will add code for 5th and 6th part today.

**Comment by daniel-kukiela** [comment]
That's great! :)
Can you acknowledge my comment above, please?

**Comment by GyanendroKh** [comment]
I think this https://github.com/Sentdex/NNfSiX/pull/129 is much better.   
Writing the utiliy methods on seperate files is better, because the matrix dot product and addition methods are replicated on all files. But having multiple files will require more steps in compilation and running the code.   

> If we are to put multiple files, we might as well consider using a build system gradle or maven.

**Comment by khushit-shah** [comment]
@daniel-kukiela  I will write each part in separate files.  But as ve go ahead code will get bigger and bigger.

**Comment by daniel-kukiela** [comment]
Right, there is also #129 and #105, so I'll call @tjf801 @plop91 here as well. We have to decide which implementation to use.

@khushit-shah I know, but that's exactly what we are doing with the book and how this tutorial will follow it. There are a few reasons why this would be better.

@GyanendroKh Thank you for your vote.

**Comment by GyanendroKh** [comment]
#105 is for JavaScript.

**Comment by daniel-kukiela** [comment]
I checked the code again and see for example formatting changes that (like removing newlines) which are also further away from the book.
Because of this, no further response, and #129 following our guidelines and being much closer to the book, I'm going to accept #129.
Thank you for your commitment though.

**Pull request closed without merging**
