### PR TITLE
Update p004-Layers-and-Object.py

### PR DESCRIPTION
**Pull request by Gstar1525**

### CODE REVIEW

**Comment by robbiemu** [comment]
Totally understand this correction but disagree here. The problem is that this should be sample code matching content in the video (shouldn't it)?

It actually brings up a question, as there are in a couple of these videos substantial midpoints where the previous lesson is refined, before switching gears. our examples don't show the midpoint code. Wondering if there is a place for it

**Comment by Gstar1525** [comment]
I just made the pull request to make the code more dynamic...Sentdex must show all the changes made in between videos in the next coming videos.

**Comment by Gstar1525** [comment]
> Totally understand this correction but disagree here. The problem is that this should be sample code matching content in the video (shouldn't it)?
> 
> It actually brings up a question, as there are in a couple of these videos substantial midpoints where the previous lesson is refined, before switching gears. our examples don't show the midpoint code. Wondering if there is a place for it

I just made the pull request to make the code more dynamic...Sentdex must show all the changes made in between videos in the next coming videos.

**Comment by Sentdex** [comment]
Showing the midpoint code is not really necessary IMO. The idea is to just simply break down the parts by the most relevant code, which is almost certainly going to just be the ending code. This isn't meant to be a repo that shows all of the possible code from the series, instead it's just meant to show NNFS in other languages, where we use the ending part's from Python in other languages. I think this is the cleanest possible way to go about doing this.

**Comment by Gstar1525** [comment]
Done

**Pull request closed without merging**
