### PR TITLE
Initial commit for avr assembly. Need help!

### PR DESCRIPTION
**Pull request by MxFxM**
I try to implement the neural network in assembly for avr.
More specific for an Attiny85.
There is not even a multiply function, so this is a challenge.
Only integer values are supported.

### CODE REVIEW

**Comment by Sentdex** [comment]
I'll let this through for now. I have no idea how to verify this. Hopefully at some point we can get another person who can take part with you lol.

**Comment by MxFxM** [comment]
I can try to compile and upload it to a board tomorrow. But I will need help at least to verify the multiplication function I wrote.

**Comment by DelSquared** [comment]
Holy cow this is an ambitious project. I'm very impressed at how you managed to do this in less than a day tbh

**Comment by clubPenguin420** [comment]
lmao, I put a joke comment on the part 3 video thinking no one would actually do it

**Comment by MxFxM** [comment]
So I was able to assemble it using avra without any errors. I also tried flashing it to the µc but then I noticed that I have used up all my Attiny85. So I will have to add the register map for the Attiny44 before I can test the output. I'm on it right now. Might take a couple of hours...

**Pull request merged**
