### PR TITLE
Use std::array

### PR DESCRIPTION
**Pull request by xorz57**
Its much safer than C arrays!

### CODE REVIEW

**Review by daniel-kukiela — COMMENTED** [review]
I'm not sure if I understand this change.

It looks like only a visual thing and it does not match the Python (and book) code as well as it was before.

**Comment by daniel-kukiela** [comment]
p002 looks like also only visual changes making it more different from the book's code.
p003 seems to be completely re-done, and for example weights, a vector of vectors, is now a plain vector, and I'm not sure if I'm a fan of this solution - this and some other changes might actually be confusing for other people as they won't match the book.

**Comment by daniel-kukiela** [comment]
@nskobelevs @PragunSaini This is changing your code, what do you think about the changes?

**Comment by nskobelevs** [comment]
> @nskobelevs @PragunSaini This is changing your code, what do you think about the changes?

I'm not invested in this repo anymore so I don't mind!

**Comment by xorz57** [comment]
I am not interested in this repo either.

**Pull request closed without merging**
