### PR TITLE
Dot Product in Kotlin

### PR DESCRIPTION
**Pull request by KisanThapa**
Following changes were made in this pull request:
1. fun main() was missing in P001BasicNeuron3Inputs.kt and P002BasicNeuronLayer.kt. So I also fixed those files.
2. Dot Product for Kotlin is added
3. Dart Programming Language added (along with all Dart codes).

### CODE REVIEW

**Comment by clubPenguin420** [comment]
You only need to commit P003, the others are already in

**Comment by clubPenguin420** [comment]
Also thanks for doing the dot product, I was stuck on one simple bug: No set method providing array access

**Comment by KisanThapa** [comment]
@clubPenguin420  fun main() was missing in P001BasicNeuron3Inputs.kt and P002BasicNeuronLayer.kt. So I also fixed those files.

**Comment by clubPenguin420** [comment]
Oh, I have a pull request fixing that, well I'll just close my two requests as I would rather have just one PR that fixes both things

**Comment by KisanThapa** [comment]
> Oh, I have a pull request fixing that, well I'll just close my two requests as I would rather have just one PR that fixes both things

@clubPenguin420  Thanks. That would be great.

**Comment by KisanThapa** [comment]
All three files for Dart Programming language has been created.

**Comment by KisanThapa** [comment]
Hey @Sentdex , Please merge this pull request. This contains Dot Product for Kotlin and p001 to p003 of Dart language. Thank You,

**Pull request merged**
