### PR TITLE
p006 swift

### PR DESCRIPTION
**Pull request by robbiemu**
a quick conversion of python p006 file

### CODE REVIEW

**Comment by robbiemu** [comment]
fyi this pr would be considerably shorter if my p005 was already in master

**Comment by daniel-kukiela** [comment]
I'm still going through PRs and trying to solve them.
What I see here is that you are trying to commit multiple files, so I want to ask you to merge these files and keep it in a single file per video part - the same way as we are going in the book. I understand that some parts of the code are going to be duplicated and that's ok - this solves multiple problems. I hope that you understand :)
Thank you.

PS. If p.5 is made the same way, I'm going to leave a similar message there as well.

**Comment by robbiemu** [comment]
I think you will understand my intent when you look at #5. I am using a separate file, but just like the python code does.

**Comment by daniel-kukiela** [comment]
The reason why we are using NNFS package, which is a package that you can just "pip install" and import is because of the book - we did not intend to explain how we are making these datasets, also this package does more than holds the dataset - ensures results repeatability and contains some tool for the book.
With this repository our goal is to keep whole lesson in a single file as well - of something cannot be imported, like NumPy, because it's not a well-known package from the repository (again NNFS does not count as it serves multiple purposes), it should be contained within the script itself. This way we can ensure backward compatibility (what if you change something and it breaks something in older lessons?), we avoid confusion (what to download to run the code), we don't have to worry if you stop committing to the repository and someone else takes it over, etc. There are a few more reasons, but to make it easy for us to maintain and for people to use, we agreed to the format that I asked you about. I understand why you split the code into separate files, I would normally do the same, but this repository needs to follow some rules.
Does this make sense?

**Comment by daniel-kukiela** [comment]
Thank you!

**Pull request merged**
